project:
  type: website

website:
  title: "ISSS608 Jia Peng Tiny World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: "Hands-On Exercise"
        menu:
        - text: "Hands-On Exercise 0"
          href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
        - text: "Hands-On Exercise 1"
          href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
        - text: "Hands-On Exercise 2"
          href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 1"
          href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
        - text: "In-Class Exercise 2"
          href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
        - text: "In-Class Exercise 2 (Tableau)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex02_17377903625070/Dashboard1
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-home Exercise 1"
          href: Take-home_Ex1.html

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

