project:
  type: website

website:
  title: "ISSS608 Jia Peng Tiny World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: "Hands-On Exercise"
        menu:
        - text: "Hands-On Exercise 0 (Introduction to Tidyverse)"
          href: Hands-on_Ex/Hands-on_Ex00/Hands-on_Ex00.html
        - text: "Hands-On Exercise 1 (ggplot2 Methods)"
          href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
        - text: "Hands-On Exercise 2 (ggplot2 and Multiple Graphs)"
          href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
        - text: "Hands-On Exercise 3a (Interactive Visualisations)"
          href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html
        - text: "Hands-On Exercise 3b (Animated Statistical Graphics)"
          href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html
        - text: "Hands-On Exercise 4a (Visualising Distributions)"
          href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html
        - text: "Hands-On Exercise 4b (Statistical Analysis)"
          href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html
        - text: "Hands-On Exercise 4c (Visualising Uncertainty)"
          href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html
        - text: "Hands-On Exercise 4d (Funnel Plots)"
          href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html
        - text: "Hands-On Exercise 5a (Ternary Plot)"
          href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html
        - text: "Hands-On Exercise 5b (Correlation Analysis)"
          href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html
        - text: "Hands-On Exercise 5c (Heatmap Visualisation)"
          href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html
        - text: "Hands-On Exercise 5d (Parallel Coordinates Plot)"
          href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html
        - text: "Hands-On Exercise 5e (Treemap Visualisation)"
          href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html
        - text: "Hands-On Exercise 7 (Time-Oriented Data Visualisation)"
          href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html
        - text: "Hands-On Exercise 8a (Choropleth Mapping with R)"
          href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08a.html
        - text: "Hands-On Exercise 8b (Visualising Geospatial Point Data)"
          href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08b.html
        - text: "Hands-On Exercise 8c (Analytical Mapping)"
          href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08c.html
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 1 (Sales & Profit Report)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex01_17371865820910/Dashboard1
        - text: "In-Class Exercise 2 (Interactive Report Dashboard)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex02_17377903625070/Dashboard1
        - text: "In-Class Exercise 3 (Interactive Dashboard)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex03-1_17383926050260/DashboardbyYearState
        - text: "In-Class Exercise 3 (Animation)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex03-2_17383925206230/SalesvsProfitbyMonthandYear
        - text: "In-Class Exercise 3 (Story)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex03-3_17383934113260/Story
        - text: "In-Class Exercise 4 (Box Plot)"
          href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
        - text: "In-Class Exercise 5 (Regression Model)"
          href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
        - text: "In-Class Exercise 6 (Histogram on Shiny App)"          
          href: https://jpchua.shinyapps.io/In-class_Ex06/
        - text: "In-Class Exercise 7 (Time-Series Data)"
          href: In-class_Ex/In-class_Ex07/In-class_Ex07.html
        - text: "In-Class Exercise 8a (SG Pools Map Visualisation)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex08_17420191461700/SGPoolsMap
        - text: "In-Class Exercise 8b (SG Property Transactions)"
          href: https://public.tableau.com/app/profile/jia.peng.chua/viz/In-class_Ex08SGPropertyTransactions/SGRealEstateTransactions
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-home Exercise 1 (Heart Attack in Japan - Youth vs Adult)"
          href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
        - text: "Take-home Exercise 2 (Singapore's International Trade)"
          href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

